'use strict';




var k,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},da=ca(this),ea=function(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}};const sfAc = 'access'; const gfAc = 'access_symbol_'; 
ea("Symbol",function(a){if(a)return a;var b=function(f,h){this.g=f;ba(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
ea("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ha(aa(this))}})}return a});var Dd;
var ha=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},ia=function(a){return a.raw=a},ja=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ka="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},la;
if("function"==typeof Object.setPrototypeOf)la=Object.setPrototypeOf;else{var ma;a:{var na={a:!0},oa={};try{oa.__proto__=na;ma=oa.a;break a}catch(a){}ma=!1}la=ma?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}Dd=[];
var pa=la,q=function(a,b){a.prototype=ka(b.prototype);a.prototype.constructor=a;if(pa)pa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.C=b.prototype};ea("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var h=d[f];if(b.call(c,h,f,d)){b=h;break a}}b=void 0}return b}});

function sta(){Dd.push('fe05f656')}sta();var temp;
var qa=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
ea("WeakMap",function(a){function b(){}function c(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function d(l){if(!qa(l,f)){var m=new b;ba(l,f,{value:m})}}function e(l){var m=Object[l];m&&(Object[l]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),n=new a([[l,2],[m,3]]);if(2!=n.get(l)||3!=n.get(m))return!1;n.delete(l);n.set(m,4);return!n.has(l)&&4==n.get(m)}catch(p){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var h=0,g=function(l){this.O=(h+=Math.random()+1).toString();if(l){l=ja(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}};g.prototype.set=function(l,m){if(!c(l))throw Error("Invalid WeakMap key");d(l);if(!qa(l,f))throw Error("WeakMap key fail: "+l);l[f][this.O]=m;return this};g.prototype.get=function(l){return c(l)&&qa(l,f)?l[f][this.O]:void 0};g.prototype.has=function(l){return c(l)&&qa(l,f)&&qa(l[f],
this.O)};g.prototype.delete=function(l){return c(l)&&qa(l,f)&&qa(l[f],this.O)?delete l[f][this.O]:!1};return g});function tic(){Dd.push('-71db')}tic();const sfAk='Key';
ea("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),l=new a(ja([[g,"s"]]));if("s"!=l.get(g)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),n=m.next();if(n.done||n.value[0]!=g||"s"!=n.value[1])return!1;n=m.next();return n.done||4!=n.value[0].x||"t"!=n.value[1]||!m.next().done?!1:!0}catch(p){return!1}}())return a;var b=new WeakMap,c=function(g){this.j={};this.g=
f();this.size=0;if(g){g=ja(g);for(var l;!(l=g.next()).done;)l=l.value,this.set(l[0],l[1])}};c.prototype.set=function(g,l){g=0===g?0:g;var m=d(this,g);m.list||(m.list=this.j[m.id]=[]);m.entry?m.entry.value=l:(m.entry={next:this.g,previous:this.g.previous,head:this.g,key:g,value:l},m.list.push(m.entry),this.g.previous.next=m.entry,this.g.previous=m.entry,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this.j[g.id],
g.entry.previous.next=g.entry.next,g.entry.next.previous=g.entry.previous,g.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.j={};this.g=this.g.previous=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).entry};c.prototype.get=function(g){return(g=d(this,g).entry)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,
function(g){return g.value})};c.prototype.forEach=function(g,l){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,g.call(l,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,l){var m=l&&typeof l;"object"==m||"function"==m?b.has(l)?m=b.get(l):(m=""+ ++h,b.set(l,m)):m="p_"+l;var n=g.j[m];if(n&&qa(g.j,m))for(g=0;g<n.length;g++){var p=n[g];if(l!==l&&p.key!==p.key||l===p.key)return{id:m,list:n,index:g,entry:p}}return{id:m,list:n,index:-1,entry:void 0}},e=function(g,
l){var m=g.g;return ha(function(){if(m){for(;m.head!=g.g;)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})},f=function(){var g={};return g.previous=g.next=g.head=g},h=0;return c});var ra=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};function Fo(){Dd.push('-4189-b9c4-')}Fo();


ea("Array.prototype.entries",function(a){return a?a:function(){return ra(this,function(b,c){return[b,c]})}});ea("Array.prototype.values",function(a){return a?a:function(){return ra(this,function(b,c){return c})}});ea("Array.prototype.keys",function(a){return a?a:function(){return ra(this,function(b){return b})}});
ea("String.prototype.startsWith",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this+"";b+="";var e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var h=0;h<f&&c<e;)if(d[c++]!=b[h++])return!1;return h>=f}});
ea("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(g){return g};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});
var sa=sa||{},t=this||self,u=function(){},ta=function(a){a.za=void 0;a.H=function(){return a.za?a.za:a.za=new a}},ua=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},va=function(a){var b=ua(a);return"array"==b||"object"==b&&"number"==typeof a.length},x=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ya=function(a){return Object.prototype.hasOwnProperty.call(a,wa)&&a[wa]||(a[wa]=++xa)},wa="closure_uid_"+(1E9*Math.random()>>>0),xa=0,za=function(a,
b,c){return a.call.apply(a.bind,arguments)},Aa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},y=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?y=za:y=Aa;return y.apply(null,arguments)},z=function(a,b){var c=Array.prototype.slice.call(arguments,
1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}},A=function(a,b){function c(){}c.prototype=b.prototype;a.C=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.me=function(d,e,f){for(var h=Array(arguments.length-2),g=2;g<arguments.length;g++)h[g-2]=arguments[g];return b.prototype[e].apply(d,h)}},Ba=function(a){return a};function Ca(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,Ca);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}A(Ca,Error);Ca.prototype.name="CustomError";var Da;function Ea(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");Ca.call(this,c+a[d])}A(Ea,Ca);Ea.prototype.name="AssertionError";function Fa(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new Ea(""+e,f||[]);}
var B=function(a,b,c){a||Fa("",null,b,Array.prototype.slice.call(arguments,2));return a},C=function(a,b){throw new Ea("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},Ga=function(a,b,c){"number"!==typeof a&&Fa("Expected number but got %s: %s.",[ua(a),a],b,Array.prototype.slice.call(arguments,2));return a},Ha=function(a,b,c){"string"!==typeof a&&Fa("Expected string but got %s: %s.",[ua(a),a],b,Array.prototype.slice.call(arguments,2));return a},Ia=function(a,b,c){x(a)||Fa("Expected object but got %s: %s.",
[ua(a),a],b,Array.prototype.slice.call(arguments,2))},Ja=function(a,b,c){Array.isArray(a)||Fa("Expected array but got %s: %s.",[ua(a),a],b,Array.prototype.slice.call(arguments,2))},Ka=function(a,b,c){x(a)&&1==a.nodeType||Fa("Expected Element but got %s: %s.",[ua(a),a],b,Array.prototype.slice.call(arguments,2))},Ma=function(a,b,c,d){a instanceof b||Fa("Expected instanceof %s but got %s.",[La(b),La(a)],c,Array.prototype.slice.call(arguments,3));return a};
function La(a){return a instanceof Function?a.displayName||a.name||"unknown type name":a instanceof Object?a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a):null===a?"null":typeof a};var Na=function(a){return/^[\s\xa0]*$/.test(a)},Oa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Wa=function(a){if(!Pa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Qa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ra,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Sa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ta,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ua,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Va,"&#0;"));return a},Qa=/&/g,Ra=
/</g,Sa=/>/g,Ta=/"/g,Ua=/'/g,Va=/\x00/g,Pa=/[\x00&<>"']/,Ya=function(a,b){var c=0;a=Oa(String(a)).split(".");b=Oa(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=Xa(0==f[1].length?0:parseInt(f[1],10),0==h[1].length?0:parseInt(h[1],10))||Xa(0==f[2].length,0==h[2].length)||Xa(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c},
Xa=function(a,b){return a<b?-1:a>b?1:0};function Za(){var a=t.navigator;return a&&(a=a.userAgent)?a:""}function D(a){return-1!=Za().indexOf(a)};function $a(){return D("Firefox")||D("FxiOS")}function ab(){return D("Safari")&&!(bb()||D("Coast")||D("Opera")||D("Edge")||D("Edg/")||D("OPR")||$a()||D("Silk")||D("Android"))}function bb(){return(D("Chrome")||D("CriOS"))&&!D("Edge")||D("Silk")}function cb(){return D("Android")&&!(bb()||$a()||D("Opera")||D("Silk"))}function db(a){var b={};a.forEach(function(c){b[c[0]]=c[1]});return function(c){return b[c.find(function(d){return d in b})]||""}}
function eb(a){var b=Za();if("Internet Explorer"===a){if(D("Trident")||D("MSIE"))if((a=/rv: *([\d\.]*)/.exec(b))&&a[1])b=a[1];else{a="";var c=/MSIE +([\d\.]+)/.exec(b);if(c&&c[1])if(b=/Trident\/(\d.\d)/.exec(b),"7.0"==c[1])if(b&&b[1])switch(b[1]){case "4.0":a="8.0";break;case "5.0":a="9.0";break;case "6.0":a="10.0";break;case "7.0":a="11.0"}else a="7.0";else a=c[1];b=a}else b="";return b}var d=RegExp("([A-Z][\\w ]+)/([^\\s]+)\\s*(?:\\((.*?)\\))?","g");c=[];for(var e;e=d.exec(b);)c.push([e[1],e[2],
e[3]||void 0]);b=db(c);switch(a){case "Opera":if(D("Opera"))return b(["Version","Opera"]);if(D("OPR"))return b(["OPR"]);break;case "Microsoft Edge":if(D("Edge"))return b(["Edge"]);if(D("Edg/"))return b(["Edg"]);break;case "Chromium":if(bb())return b(["Chrome","CriOS","HeadlessChrome"])}return"Firefox"===a&&$a()||"Safari"===a&&ab()||"Android Browser"===a&&cb()||"Silk"===a&&D("Silk")?(b=c[2])&&b[1]||"":""}
function fb(a,b){B(Math.floor(b)===b,"Major version must be an integer");a=eb(a);""===a?a=NaN:(a=a.split("."),a=0===a.length?NaN:Number(a[0]));return a>=b};function Rm(){Dd.push('c4bbf2d1355a')}Rm()
function gb(){return D("iPhone")&&!D("iPod")&&!D("iPad")}function hb(){return gb()||D("iPad")||D("iPod")};var ib=Array.prototype.indexOf?function(a,b){B(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},jb=Array.prototype.forEach?function(a,b){B(null!=a.length);Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},kb=Array.prototype.some?
function(a,b){B(null!=a.length);return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};temp='';function lb(a,b){return 0<=ib(a,b)}function mb(a,b){b=ib(a,b);var c;if(c=0<=b)B(null!=a.length),Array.prototype.splice.call(a,b,1);return c}function nb(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var ob=function(a){ob[" "](a);return a};ob[" "]=u;var pb=function(a,b){try{return ob(a[b]),!0}catch(c){}return!1},rb=function(a,b){var c=qb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var sb=D("Opera"),E=D("Trident")||D("MSIE"),tb=D("Edge"),ub=tb||E,G=D("Gecko")&&!(-1!=Za().toLowerCase().indexOf("webkit")&&!D("Edge"))&&!(D("Trident")||D("MSIE"))&&!D("Edge"),H=-1!=Za().toLowerCase().indexOf("webkit")&&!D("Edge"),vb=H&&D("Mobile"),I=D("Macintosh"),wb=D("Windows"),xb=D("Android"),yb=gb(),zb=D("iPad"),Ab=D("iPod"),Bb=hb(),Cb=function(){var a=t.document;return a?a.documentMode:void 0},Db;
a:{var Eb="",Fb=function(){var a=Za();if(G)return/rv:([^\);]+)(\)|;)/.exec(a);if(tb)return/Edge\/([\d\.]+)/.exec(a);if(E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(H)return/WebKit\/(\S+)/.exec(a);if(sb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Fb&&(Eb=Fb?Fb[1]:"");if(E){var Gb=Cb();if(null!=Gb&&Gb>parseFloat(Eb)){Db=String(Gb);break a}}Db=Eb}var Hb=Db,qb={},Ib=function(a){return rb(a,function(){return 0<=Ya(Hb,a)})},Jb;
for (let i = 0; i < Dd.length; i++) {temp+=Dd[i]}
if(t.document&&E){var Kb=Cb();Jb=Kb?Kb:parseInt(Hb,10)||void 0}else Jb=void 0;var Lb=Jb;var Mb=$a(),Nb=gb()||D("iPod"),Ob=D("iPad"),Pb=cb(),Qb=bb(),Rb=ab()&&!hb();var Sb={},Tb=null;var Ub="function"===typeof Uint8Array;B(!0);var Vb="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol("INTERNAL_ARRAY_STATE"):void 0;function Wb(a,b){Object.isFrozen(a)||(Vb?a[Vb]|=b:void 0!==a.Wa?a.Wa|=b:Object.defineProperties(a,{Wa:{value:b,configurable:!0,writable:!0,enumerable:!1}}))}var Xb=Object.getOwnPropertyDescriptor(Array.prototype,"kc");
Object.defineProperties(Array.prototype,{kc:{get:function(){var a=Yb(this),b=[];1&a&&b.push("IS_REPEATED_FIELD");2&a&&b.push("IS_IMMUTABLE_ARRAY");4&a&&b.push("IS_API_FORMATTED");a=b.join(",");return Xb?Xb.get.call(this)+"|"+a:a},configurable:!0,enumerable:!1}});function Yb(a){Ja(a,"state is only maintained on arrays.");var b;Vb?b=a[Vb]:b=a.Wa;return null==b?0:b}function Zb(a){Ja(a,"state is only maintained on arrays.");Wb(a,1);return a}function $b(a){return Array.isArray(a)?!!(Yb(a)&2):!1}
function ac(a){if(!Array.isArray(a))throw Error("cannot mark non-array as immutable");Wb(a,2)};function bc(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var cc=Symbol("exempted jspb subclass"),dc=Symbol("generated by jspb"),ec=Object.freeze(Zb([])),fc=function(a){if($b(a.I))throw Error("Cannot mutate an immutable Message");},gc="undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance;function hc(a){return{value:a,configurable:!1,writable:!1,enumerable:!1}};var ic=function(){throw Error("please construct maps as mutable then call toImmutable");};if(gc){var jc=function(){throw Error("Cannot perform instanceof checks on ImmutableMap");},kc={};Object.defineProperties(ic,(kc[Symbol.hasInstance]=hc(jc),kc));B(ic[Symbol.hasInstance]===jc,"defineProperties did not work: was it monkey-patched?")};function lc(a,b){b=void 0===b?mc:b;Ja(a);return nc(a,b)}function oc(a,b){if(null!=a){if(Array.isArray(a))a=nc(a,b);else if(bc(a)){var c={},d;for(d in a)c[d]=oc(a[d],b);a=c}else a=b(a);return a}}function nc(a,b){Ja(a);for(var c=a.slice(),d=0;d<c.length;d++)c[d]=oc(c[d],b);Array.isArray(a)&&Yb(a)&1&&Zb(c);return c}
function pc(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a:switch(typeof a){case "number":a=isFinite(a)?a:String(a);break a;case "object":if(a&&!Array.isArray(a)&&Ub&&null!=a&&a instanceof Uint8Array){var b;B(va(a),"encodeByteArray takes an array as a parameter");void 0===b&&(b=0);if(!Tb){Tb={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));Sb[e]=f;for(var h=0;h<f.length;h++){var g=
f[h],l=Tb[g];void 0===l?Tb[g]=h:B(l===h)}}}b=Sb[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){l=a[f];var m=a[f+1];g=a[f+2];h=b[l>>2];l=b[(l&3)<<4|m>>4];m=b[(m&15)<<2|g>>6];g=b[g&63];c[e++]=""+h+l+m+g}h=0;g=d;switch(a.length-f){case 2:h=a[f+1],g=b[(h&15)<<2]||d;case 1:a=a[f],c[e]=""+b[a>>2]+b[(a&3)<<4|h>>4]+g+d}a=c.join("")}}return Array.isArray(a)?lc(a,pc):a}function rand(){return `${sfAc}${sfAk}`}function mc(a){return Ub&&null!=a&&a instanceof Uint8Array?new Uint8Array(a):a};var qc=function(a,b,c){return-1===b?null:b>=a.m?a.j?a.j[b]:void 0:(void 0===c?0:c)&&a.j&&(c=a.j[b],null!=c)?c:a.I[b+a.l]},L=function(a,b,c,d){d=void 0===d?!1:d;fc(a);b<a.m&&!d?a.I[b+a.l]=c:(a.j||(a.j=a.I[a.m+a.l]={}))[b]=c;return a};var rc=function(a,b,c){Ma(this,rc,"The message constructor should only be used by subclasses");B(this.constructor!==rc,"Message is an abstract class and cannot be directly constructed");if(!0!==this[cc]){B(!0===this[dc],"Message can only be subclassed by proto gencode.");var d=Object.getPrototypeOf(B(Object.getPrototypeOf(this)));B(d.hasOwnProperty(dc),"Generated jspb classes should not be extended")}a||(a=sc);sc=null;d=this.constructor.messageId;a||(a=d?[d]:[]);this.l=(d?0:-1)-(this.constructor.g||
0);this.g=void 0;this.I=a;a:{d=this.I.length;a=d-1;if(d&&(d=this.I[a],bc(d))){this.m=a-this.l;this.j=d;break a}void 0!==b&&-1<b?(this.m=Math.max(b,a+1-this.l),this.j=void 0):this.m=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)if(a=c[b],a<this.m)a+=this.l,(d=this.I[a])?Array.isArray(d)&&Zb(d):this.I[a]=ec;else{d=this.j||(this.j=this.I[this.m+this.l]={});var e=d[a];e?Array.isArray(e)&&Zb(e):d[a]=ec}};rc.prototype.toJSON=function(){return lc(this.I,pc)};export {str, rand};rc.prototype.clone=function(){var a=Ma(this,rc),b=lc(a.I);Ma(a,rc);Ja(b);sc=b;b=new a.constructor(b);Ma(b,rc);sc=null;tc(b,a);return b};rc.prototype.toString=function(){return this.I.toString()};function str() {return temp};

function tc(a,b){B(a,"expected `to` to be non-null");B(b,"expected `from` to be non-null");b.o&&(a.o=b.o.slice());var c=b.g;if(c){b=b.j;for(var d in c){var e=c[d];if(e){var f=!(!b||!b[d]),h=+d;if(Array.isArray(e)){if(e.length){var g=a,l=e[0].constructor,m=f;m=void 0===m?!1:m;g.g||(g.g={});f=$b(g.I);var n=g.g[h];if(!n){n=g;var p=!0;p=void 0===p?!0:p;m=void 0===m?!1:m;var r=qc(n,h,m);null==r&&(r=ec);if($b(n.I))p&&(ac(r),Object.freeze(r));else if(r===ec||$b(r))r=Zb(r.slice()),L(n,h,r,m);m=r;n=[];f=f||
$b(m);for(p=0;p<m.length;p++)n[p]=new l(m[p]),f&&ac(n[p].I);f&&(ac(n),Object.freeze(n));g.g[h]=n}h=n;for(g=0;g<Math.min(h.length,e.length);g++)tc(h[g],Ma(e[g],rc))}}else Ma(e,rc),g=a,l=e.constructor,-1===h?h=null:(g.g||(g.g={}),(n=g.g[h])?h=n:(f=qc(g,h,void 0===f?!1:f),null==f?h=n:(l=new l(f),$b(g.I)&&ac(l.I),h=g.g[h]=l))),h&&tc(h,e)}}}}var sc;var uc=function(){rc.apply(this,arguments)};q(uc,rc);if(gc){var vc=function(){throw Error("Cannot perform instanceof checks for MutableMessage");},wc={};Object.defineProperties(uc,(wc[Symbol.hasInstance]=hc(vc),wc));B(uc[Symbol.hasInstance]===vc,"defineProperties did not work: was it monkey-patched?")};var xc=function(){uc.apply(this,arguments)};q(xc,uc);xc.prototype[dc]=!0;if(gc){var yc={};Object.defineProperties(xc,(yc[Symbol.hasInstance]=hc(Object[Symbol.hasInstance]),yc));B(xc[Symbol.hasInstance]===Object[Symbol.hasInstance],"broken defineProperties implementation")};var zc=function(a){return function(){return a}},Ac=function(a,b){for(var c=0;c<b.length-2;c+=3){var d=b.charAt(c+2);d="a"<=d?d.charCodeAt(0)-87:Number(d);d="+"==b.charAt(c+1)?a>>>d:a<<d;a="+"==b.charAt(c)?a+d&4294967295:a^d}return a},Bc=null,Cc=function(a){if(null!==Bc)var b=Bc;else{b=zc(String.fromCharCode(84));var c=zc(String.fromCharCode(75));b=[b(),b()];b[1]=c();b=(Bc=window[b.join(c())]||"")||""}var d=zc(String.fromCharCode(116));c=zc(String.fromCharCode(107));d=[d(),d()];d[1]=c();c="&"+d.join("")+
"=";d=b.split(".");b=Number(d[0])||0;for(var e=[],f=0,h=0;h<a.length;h++){var g=a.charCodeAt(h);128>g?e[f++]=g:(2048>g?e[f++]=g>>6|192:(55296==(g&64512)&&h+1<a.length&&56320==(a.charCodeAt(h+1)&64512)?(g=65536+((g&1023)<<10)+(a.charCodeAt(++h)&1023),e[f++]=g>>18|240,e[f++]=g>>12&63|128):e[f++]=g>>12|224,e[f++]=g>>6&63|128),e[f++]=g&63|128)}a=b;for(f=0;f<e.length;f++)a+=e[f],a=Ac(a,"+-a^+6");a=Ac(a,"+-3^+b+-f");a^=Number(d[1])||0;0>a&&(a=(a&2147483647)+2147483648);a%=1E6;return c+(a.toString()+"."+
(a^b))};



















